import Document, {Html, Head, Main, NextScript} from 'next/document'
import React from "react";

export default class MyDocument extends Document {
    render() {
        return (
            <Html>
                <Head>
                    <meta name="keywords" content="revcount"/>
                    <meta name="description" content="Revcount project"/>
                    <meta charSet="utf-8"/>
                    <meta name="description" content="Generated by create next app"/>
                    <link rel="icon" href="/favicon.ico"/>
                    <link rel="stylesheet" href="/libs/normalize.css"/>
                </Head>
                <title>
                    Revcount
                </title>
                        <Main/>
                        <NextScript/>
                <body>
                </body>
            </Html>
        )
    }
}